/* Catalogue du matériel : 83 références. Prix relevés le 30/09/2026 sur les pages indiquées (price_status = « relevé »)
   ou estimés (base expliquée dans note). Les prix changent : vérifiez avant achat. Les champs url et note gardent la provenance des prix de référence (non affichée) ; tip est le conseil affiché.
   Les produits proposés à l'achat, en 3 gammes de budget avec liens Amazon, sont dans js/gear-tiers.js. */
window.GEAR = [
{
"id": "G001",
"category": "Sac",
"name": "Sac à dos 45-55 L",
"model": "Osprey Exos 48 Homme",
"qty": 1,
"weight_g": 1255,
"price_eur": 219.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/14738-2885-sac-a-dos-de-randonnee-osprey-exos-48-homme-gris.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Poids 1255-1294 g selon taille. Entrée de gamme : Wilsa Trekker 55, 94,95 €, 2140 g (relevé) https://www.rayonrando.com/fr/sacs-a-dos-de-randonnee-50-55-l/2775-sac-a-dos-trekker-55.html . Alternative Decathlon Forclaz MT500 Air 50+10 L ≈114,99 € (estimation : extrait moteur de recherche, page decathlon.fr bloquée 403) https://www.decathlon.fr/search?Ntt=sac+trekking+50+L",
"tip": "Essayez-le chargé : réglez le dos à votre taille."
},
{
"id": "G002",
"category": "Sac",
"name": "Housse de pluie sac à dos",
"model": "Highlander Large Waterproof Rucksack Cover",
"qty": 1,
"weight_g": 110,
"price_eur": 14.9,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/protections-sacs-a-dos/3316-housse-de-pluie-large-waterproof-rucksack-cover-camouflage.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Recommandé : Osprey Ultralight Raincover à partir de 42,95 € (112-125 g) https://www.lyophilise.fr/11289-200-housse-de-pluie-osprey-ultralight.html",
"tip": ""
},
{
"id": "G003",
"category": "Sac",
"name": "Sac étanche intérieur (sac de compression/rangement)",
"model": "Osprey UL Dry Sack 12",
"qty": 2,
"weight_g": null,
"price_eur": 21.9,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/sacs-de-rangement-etanches/4906-sac-de-rangement-etanche-ul-dry-sack-12.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Protège couchage et vêtements de rechange. Poids non indiqué sur la liste.",
"tip": "Protège couchage et vêtements de rechange."
},
{
"id": "G004",
"category": "Eau",
"name": "Gourde rigide 1 L",
"model": "Nalgene Ultralite HDPE 1 L (grande ouverture)",
"qty": 2,
"weight_g": 108,
"price_eur": 12.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/11598-bouteille-grande-ouverture-nalgene-ul-hdpe-1-l.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Grande ouverture compatible filtres/pastilles.",
"tip": "Grande ouverture compatible filtres/pastilles."
},
{
"id": "G005",
"category": "Eau",
"name": "Filtre à eau",
"model": "Sawyer Squeeze SP129 (0,1 µm)",
"qty": 1,
"weight_g": null,
"price_eur": 64.99,
"price_status": "relevé",
"url": "https://www.knivesandtools.fr/fr/pt/-sawyer-squeeze-sp129-filtre-a-eau.htm",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Aussi 64,95 € chez allspares.fr https://www.allspares.fr/filtre-a-eau-sawyer-squeeze-sp129-sp129 . Entrée de gamme : Sawyer Mini à partir de 37,90 € (85 g) https://www.lyophilise.fr/9363-29287-filtre-a-eau-sawyer-mini.html . Ne filtre pas les virus ni les produits chimiques : combiner avec pastilles si doute.",
"tip": "Ne filtre pas les virus ni les produits chimiques : combiner avec pastilles si doute."
},
{
"id": "G006",
"category": "Eau",
"name": "Gourde filtrante (alternative au Sawyer)",
"model": "Katadyn BeFree AC 0,7 L",
"qty": 1,
"weight_g": 95,
"price_eur": 49.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/16008-27813-bouteille-filtrante-katadyn-befree-ac-07-l.html",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "sac",
"note": "Alternative : LifeStraw Peak Collapsible Squeeze 1 L, 48,95 € (110 g) https://www.lyophilise.fr/8137-97-filtre-a-eau-lifestraw-peak-series-collapsible-squeeze.html",
"tip": ""
},
{
"id": "G007",
"category": "Eau",
"name": "Pastilles de désinfection",
"model": "Aquatabs (NaDCC) – boîte de 50 comprimés (1 cp/L)",
"qty": 1,
"weight_g": null,
"price_eur": 5.9,
"price_status": "relevé",
"url": "https://www.materiel-aventure.fr/traitement-eau/5120-tablettes-de-purification-de-l-eau-aquatabs-en-boite-de-50-comprimes-5099668005019.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Aussi 6,00 € chez dan-military.fr. Alternative : Micropur Forte MF 1T 100 cp, 22,95 € (en rupture le 30/09) https://www.lyophilise.fr/4010-micropur-forte-mf-1t-100-comprimes-1-comp-1-l.html . Attention : Micropur CLASSIC (argent) = conservation, pas désinfection virale.",
"tip": "Attention : Micropur CLASSIC (argent) = conservation, pas désinfection virale."
},
{
"id": "G008",
"category": "Eau",
"name": "Poche à eau souple (réserve pliable / eau sale pour filtre)",
"model": "Sawyer poches souples 2 L x 2",
"qty": 1,
"weight_g": 56,
"price_eur": 14.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/8731-poches-a-eau-souple-sawyer-2-l-x-2.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Filetage compatible Sawyer Squeeze/Mini.",
"tip": "Choisir un filetage compatible avec son filtre (28 mm pour Sawyer)."
},
{
"id": "G009",
"category": "Eau",
"name": "Eau potable longue conservation (sachet)",
"model": "Eau potable en sachet 5 ans – 500 ml",
"qty": 4,
"weight_g": 500,
"price_eur": 2.9,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/4800-eau-potable-en-sachet-5-ans-500-ml.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Poids = 500 g par sachet. Délai annoncé 1 à 3 semaines. Pack 24 x 125 ml (3 L) : 19,90 € https://www.lyophilise.fr/4287-eau-potable-en-sachet-5-ans-24-x-125-ml-3-l.html",
"tip": "Environ 500 g par sachet."
},
{
"id": "G010",
"category": "Eau",
"name": "Jerrican alimentaire 20 L",
"model": "Diall 20 L blanc (alimentaire)",
"qty": 3,
"weight_g": null,
"price_eur": 16.5,
"price_status": "relevé",
"url": "https://www.castorama.fr/jerrican-alimentaire-diall-20-l-blanc/3454975928390_CAFR.prd",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "maison",
"note": "Vendu par Castorama. Version 15 L avec robinet : 12,50 €.",
"tip": ""
},
{
"id": "G011",
"category": "Eau",
"name": "Bidon de stockage avec robinet",
"model": "Diall jerrican alimentaire 35 L avec robinet",
"qty": 1,
"weight_g": null,
"price_eur": 21.9,
"price_status": "relevé",
"url": "https://www.castorama.fr/jerrican-alimentaire-35-l-diall-avec-robinet/3454975928451_CAFR.prd",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "maison",
"note": "Note clients moyenne 3,08/5 (23 avis) sur la page : vérifier l'étanchéité du robinet.",
"tip": ""
},
{
"id": "G012",
"category": "Eau",
"name": "Eau en bouteille (stock)",
"model": "6 L par personne pour 72 h (SGDSN) — ex. pack 6 × 1 L",
"qty": 1,
"weight_g": null,
"price_eur": 3,
"price_status": "estimation",
"url": "https://www.auchan.fr/cristaline-eau-de-source-plate-bouteilles/pr-C1206322",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "maison",
"note": "Prix estimé pour 6 L (≈ 0,25-0,50 €/L en grande surface, non relevé). Multiplier par le nombre de personnes et par la durée visée (voir le calculateur de l'onglet Écosystème).",
"tip": "Multiplier par le nombre de personnes et par la durée visée (voir le calculateur de l'onglet Écosystème)."
},
{
"id": "G013",
"category": "Eau",
"name": "Conservateur pour eau stockée",
"model": "Micropur Classic MC 1000F – 100 ml pour 1000 L",
"qty": 1,
"weight_g": 147,
"price_eur": 18.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/7359-micropur-classic-mc-1000f-100-ml-pour-1000-l.html",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "maison",
"note": "Ions d'argent : empêche la recontamination de l'eau déjà potable stockée ; ne désinfecte pas une eau douteuse.",
"tip": "Ions d'argent : empêche la recontamination de l'eau déjà potable stockée ; ne désinfecte pas une eau douteuse."
},
{
"id": "G014",
"category": "Nourriture",
"name": "Repas lyophilisés",
"model": "Sélection 10 repas lyophilisés – Lyophilise & Co",
"qty": 1,
"weight_g": 960,
"price_eur": 59.08,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/16293-selection-10-repas-lyophilises-lyophilise-co.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "960 g net, ~4790 kcal au total. Pour 72 h compter 6 repas + petits-déj./encas. Variante 'Petit prix' 10 repas : 65,66 €.",
"tip": "Pour 72 h, comptez 6 repas plus petits-déjeuners et en-cas."
},
{
"id": "G015",
"category": "Nourriture",
"name": "Ration de survie compacte",
"model": "NRG-5 ration de secours 500 g (20 ans)",
"qty": 1,
"weight_g": 500,
"price_eur": 9.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/4235-ration-de-secours-nrg-5-20-ans.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Prix barré 11,05 €, remise -10 % affichée le 30/09. Entrée de gamme : Ration de survie 5 ans 500 g, 6,95 € https://www.lyophilise.fr/4799-ration-de-survie-5-ans.html",
"tip": ""
},
{
"id": "G016",
"category": "Nourriture",
"name": "Barres énergétiques / barre-repas",
"model": "Barre-repas O.K.R Pomme-cranberries 100 g",
"qty": 3,
"weight_g": 100,
"price_eur": 4.67,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/8438-barre-repas-okr-pomme-cranberries.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "387 kcal par barre.",
"tip": ""
},
{
"id": "G017",
"category": "Nourriture",
"name": "Stock lyophilisé 7 jours (seau)",
"model": "Pack 7 jours en seau Tango (8 ans)",
"qty": 1,
"weight_g": 2445,
"price_eur": 189.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/14885-pack-7-jours-en-seau-tango-repas-lyophilises-8-ans.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "maison",
"note": "Poids net 2445 g. Pour 1 mois : Pack Survie 1 mois 489,95 € https://www.lyophilise.fr/7511-pack-survie-1-mois-repas-rations-compactes-filtre-a-eau-stockage-15-ans.html",
"tip": ""
},
{
"id": "G018",
"category": "Nourriture",
"name": "Conserves (plats, légumineuses, poisson, légumes)",
"model": "Conserves du commerce 400 g",
"qty": 20,
"weight_g": null,
"price_eur": 2,
"price_status": "estimation",
"url": "https://www.auchan.fr/recherche?text=conserve",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "maison",
"note": "Prix unitaire estimé ≈ 1-3 €/boîte (non relevé : sites de grande distribution inaccessibles ou prix liés au magasin) ; 20 boîtes ≈ 40 €. Rotation FIFO, prévoir un ouvre-boîte manuel. Reportez les kcal de l'étiquette dans l'inventaire.",
"tip": "Rotation FIFO, prévoir un ouvre-boîte manuel. Reportez les kcal de l'étiquette dans l'inventaire."
},
{
"id": "G019",
"category": "Cuisson",
"name": "Réchaud à gaz ultraléger",
"model": "MSR PocketRocket 2",
"qty": 1,
"weight_g": 73,
"price_eur": 42.5,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/6606-rechaud-a-gaz-msr-pocketrocket-2.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Prix barré 50,00 € (-15 % affiché). Entrée de gamme : réchaud de poche Esbit + 20 x 4 g, 14,95 € (170 g) https://www.lyophilise.fr/8039-rechaud-de-poche-esbit-et-20-x-4-g-combustibles-solides.html",
"tip": ""
},
{
"id": "G020",
"category": "Cuisson",
"name": "Réchaud à combustible solide (secours, stockage long)",
"model": "Esbit réchaud de poche + 12 x 14 g",
"qty": 1,
"weight_g": 360,
"price_eur": 20.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/6833-rechaud-de-poche-esbit-et-12-x-14-g-combustibles-solides.html",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "les deux",
"note": "Recharge 12 x 14 g : 9,95 €.",
"tip": ""
},
{
"id": "G021",
"category": "Cuisson",
"name": "Cartouche de gaz (vissable EN417)",
"model": "Optimus Energy 230 g",
"qty": 2,
"weight_g": 380,
"price_eur": 6.75,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/4400-cartouche-de-gaz-optimus-energy-230-g.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "les deux",
"note": "Prix barré 7,50 €. Poids plein 380 g.",
"tip": ""
},
{
"id": "G022",
"category": "Cuisson",
"name": "Popote",
"model": "Toaks titane 0,75 L",
"qty": 1,
"weight_g": 103,
"price_eur": 27.86,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/9003-popote-en-titane-toaks-075-l.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Prix barré 30,95 €. Délai 1-3 semaines annoncé.",
"tip": ""
},
{
"id": "G023",
"category": "Cuisson",
"name": "Réchaud maison (coupure de gaz/électricité)",
"model": "Réchaud portable 1300 W + 4 cartouches (vendeur marketplace Castorama)",
"qty": 1,
"weight_g": null,
"price_eur": 37.91,
"price_status": "relevé",
"url": "https://www.castorama.fr/mkp/r-chaud-gaz-portable-1300w-4-cartouches-190gr-allumage-auto-s-curis-r-chaud-camping-vanlife-flamme-r-glable-black-cook/3701599337450_CAFR.prd",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "maison",
"note": "Vendu par un tiers. Alternative vendue par Castorama : Campingaz Super Carena R 3000 W, 42,90 € (nécessite une bouteille Campingaz) https://www.castorama.fr/rechaud-super-carena-r-campingaz-3000w/3138520314837_CAFR.prd . Toujours utiliser en local ventilé.",
"tip": "Toujours utiliser en local ventilé."
},
{
"id": "G024",
"category": "Cuisson",
"name": "Briquets",
"model": "BIC (lot de 2)",
"qty": 2,
"weight_g": null,
"price_eur": 1.79,
"price_status": "relevé",
"url": "https://www.action.com/fr-fr/search/?q=briquet",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Prix lu sur la page de résultats Action (fiche produit 403). Fiche : https://www.action.com/fr-fr/p/3014797/briquets-bic/",
"tip": ""
},
{
"id": "G025",
"category": "Cuisson",
"name": "Pierre à feu (ferro)",
"model": "Light My Fire Firesteel Scout bio (avec sifflet)",
"qty": 1,
"weight_g": 25,
"price_eur": 13.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/4788-114-firesteel-scout-bio-light-my-fire-pierre-a-feu-grattoir-avec-sifflet.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Version Army : 19,95 €.",
"tip": ""
},
{
"id": "G026",
"category": "Cuisson",
"name": "Allume-feu",
"model": "Light My Fire TinderSticks",
"qty": 1,
"weight_g": 200,
"price_eur": 4.5,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/4789-allume-feu-light-my-fire-tinderssticks.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "les deux",
"note": "",
"tip": ""
},
{
"id": "G027",
"category": "Abri/chaleur",
"name": "Couverture de survie",
"model": "SOL Emergency Blanket",
"qty": 2,
"weight_g": 82,
"price_eur": 7.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/6388-couverture-de-survie-sol.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Entrée de gamme : couverture BCB 2,50 € (50 g) https://www.lyophilise.fr/5421-couverture-de-survie-bcb.html",
"tip": ""
},
{
"id": "G028",
"category": "Abri/chaleur",
"name": "Sac de bivouac d'urgence",
"model": "SOL Emergency Bivvy",
"qty": 1,
"weight_g": 115,
"price_eur": 23.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/6393-bivouac-durgence-sol.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Recommandé (respirant, réutilisable) : SOL Escape Lite Bivvy 56,95 € (155 g) https://www.lyophilise.fr/8531-sac-de-bivouac-leger-escape-lite-bivvy-sol.html",
"tip": ""
},
{
"id": "G029",
"category": "Abri/chaleur",
"name": "Tarp",
"model": "DD Hammocks Tarp 3x3 m",
"qty": 1,
"weight_g": 950,
"price_eur": 41.18,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/tarps/3853-tarp-3x3-m.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Prix de base 54,90 € (-25 % affiché). Poids vérifié 950 g, 3000 mm.",
"tip": ""
},
{
"id": "G030",
"category": "Abri/chaleur",
"name": "Sac de couchage",
"model": "Millet Baikal 1100 Reg (plage 5 °C à 0 °C)",
"qty": 1,
"weight_g": 1220,
"price_eur": 114.9,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/sacs-de-couchage-5c-a-0c/1056-sac-de-couchage-baikal-1100-reg.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "les deux",
"note": "Prix de base 149,90 €. Vérifier températures confort/limite sur la fiche.",
"tip": "Vérifier températures confort/limite sur la fiche."
},
{
"id": "G031",
"category": "Abri/chaleur",
"name": "Poncho de pluie",
"model": "Poncho de secours ARVA",
"qty": 1,
"weight_g": 80,
"price_eur": 9.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/13959-poncho-de-secours-arva.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "",
"tip": ""
},
{
"id": "G032",
"category": "Vêtements",
"name": "Sous-couche thermique haut",
"model": "Damart Sport Comfort 4 Thermolactyl zippé (homme)",
"qty": 1,
"weight_g": 223,
"price_eur": 18.36,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/sous-vetements-chauds-homme/4526-t-shirt-technique-homme-comfort-4-thermolactyl-zippe.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Prix soldé (-60 %), tailles limitées. Mérinos : Icebreaker dès ~40-54 € sur rayonrando.com.",
"tip": ""
},
{
"id": "G033",
"category": "Vêtements",
"name": "Sous-couche thermique bas",
"model": "Highlander Collant thermique Long Johns",
"qty": 1,
"weight_g": null,
"price_eur": 8.4,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/sous-vetements-chauds-homme/3191-collant-thermique-long-johns.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Prix soldé (-50 %).",
"tip": ""
},
{
"id": "G034",
"category": "Vêtements",
"name": "Couche intermédiaire (polaire)",
"model": "Highlander Hirta Fleece (homme)",
"qty": 1,
"weight_g": 330,
"price_eur": 17.96,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/polaires-randonnee-homme/4171-polaire-homme-hirta-fleece-bleu.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Soldé -60 % ; au 30/09 seule la taille XS apparaissait en liste : prix non représentatif si votre taille manque (prix de base 44,90 €).",
"tip": ""
},
{
"id": "G035",
"category": "Vêtements",
"name": "Veste imperméable",
"model": "Pro-x elements Blake (homme)",
"qty": 1,
"weight_g": 350,
"price_eur": 47.97,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/vestes-randonnee-pluie-coupe-vent/3516-veste-de-randonnee-homme-blake-noire.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Prix de base 79,95 €.",
"tip": ""
},
{
"id": "G036",
"category": "Vêtements",
"name": "Bonnet",
"model": "Bonnet polaire Pootlass",
"qty": 1,
"weight_g": 30,
"price_eur": 10.9,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/bonnets-cagoules/4542-bonnet-polaire-pootlass.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "",
"tip": ""
},
{
"id": "G037",
"category": "Vêtements",
"name": "Gants",
"model": "Highlander Mountain gloves (imperméables)",
"qty": 1,
"weight_g": 132,
"price_eur": 12.45,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/gants/4163-gants-mountain-gloves.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Sous-gants mérinos Icebreaker : 14,97 € https://www.rayonrando.com/fr/gants/862-sous-gants-unisex-oasis-glove-liners.html",
"tip": ""
},
{
"id": "G038",
"category": "Vêtements",
"name": "Chaussettes de rechange",
"model": "THYO Merinos Wool Trek Mid",
"qty": 2,
"weight_g": null,
"price_eur": 14.24,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/chaussettes-de-randonnee/4980-chaussettes-merinos-wool-trek-mid.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Prix de base 18,99 €.",
"tip": ""
},
{
"id": "G039",
"category": "Lumière",
"name": "Lampe frontale",
"model": "Petzl Tikkina (piles AAA / batterie Core)",
"qty": 1,
"weight_g": 92,
"price_eur": 24.9,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/16014-27927-lampe-frontale-petzl-tikkina.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Recommandé (USB-C, 47 g) : Nitecore NU25 UL 44,90 € https://www.lyophilise.fr/12287-lampe-frontale-nitecore-nu25-ul.html",
"tip": ""
},
{
"id": "G040",
"category": "Lumière",
"name": "Frontale de secours",
"model": "Petzl e+Lite",
"qty": 1,
"weight_g": 26,
"price_eur": 27.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/8092-lampe-frontale-de-secours-petzl-elite.html",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "sac",
"note": "",
"tip": ""
},
{
"id": "G041",
"category": "Lumière",
"name": "Piles AA",
"model": "Varta Longlife Power AA (lot de 12)",
"qty": 1,
"weight_g": null,
"price_eur": 9.5,
"price_status": "relevé",
"url": "https://www.castorama.fr/pile-alcaline-aa-lr6-varta-long-life-power-lot-de-12/4008496659234_CAFR.prd",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Pour stockage long / froid : Energizer Ultimate Lithium AA x4, 13,02 € (marketplace) https://www.castorama.fr/mkp/pile-lithium-energizer-ultimate-lr6-1-5-volts-blister-de-4-piles/7638900262643_CAFR.prd . Prévoir aussi des AAA selon la frontale.",
"tip": "Prévoir aussi des AAA selon la frontale."
},
{
"id": "G042",
"category": "Lumière",
"name": "Lampe dynamo (+ radio FM + powerbank)",
"model": "XCell Radiolight Dynamo 149039",
"qty": 1,
"weight_g": null,
"price_eur": 21.99,
"price_status": "relevé",
"url": "https://www.castorama.fr/departments/xcell-radiolight-dynamo-149039-lampe-torche-multifonction-rechargeable-radio-fm-powerbank/4042883490390_CAFR.prd",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "maison",
"note": "Vendeur marketplace Castorama.",
"tip": ""
},
{
"id": "G043",
"category": "Lumière",
"name": "Lanterne LED",
"model": "Diall petite lanterne LED 2 fonctions 50 lm",
"qty": 2,
"weight_g": null,
"price_eur": 9.9,
"price_status": "relevé",
"url": "https://www.castorama.fr/petite-lanterne-led-2-fonctions-diall-50-lumens/3663602890911_CAFR.prd",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "maison",
"note": "Préférer à la bougie (risque incendie).",
"tip": "Préférer à la bougie (risque incendie)."
},
{
"id": "G044",
"category": "Énergie",
"name": "Batterie externe 10 000 mAh",
"model": "Nitecore NB10000 Gen4",
"qty": 1,
"weight_g": 143,
"price_eur": 80.66,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/11020-batterie-externe-nitecore-nb10000-gen4.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Prix barré 84,90 € (-5 %). Entrée de gamme : X-Moove Sky 10000 mAh 29,95 € (182 g) https://www.lyophilise.fr/8492-batterie-externe-x-moove-sky-10000-mah-2-ports-usb.html",
"tip": ""
},
{
"id": "G045",
"category": "Énergie",
"name": "Panneau solaire pliable",
"model": "X-Moove Trail 21 W",
"qty": 1,
"weight_g": 425,
"price_eur": 123.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/9936-panneau-solaire-portable-x-moove-trail-21-w.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "les deux",
"note": "Entrée : X-Moove Trail 14 W 89,95 € (300 g).",
"tip": ""
},
{
"id": "G046",
"category": "Énergie",
"name": "Station électrique portable",
"model": "EcoFlow RIVER 3 (ASI) – 245 Wh / 300 W",
"qty": 1,
"weight_g": null,
"price_eur": 259,
"price_status": "relevé",
"url": "https://fr.ecoflow.com/products/river-3-portable-power-station",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "maison",
"note": "Prix officiel fr.ecoflow.com (variante ASI en stock ; variante standard 249 € en rupture). Bundle + panneau 45 W : 279 €. Alternatives Jackery (prix officiels fr.jackery.com) : Explorer 240 v2 199 €, Explorer 300 Plus 279 €, Explorer 500 v2 299 €, Explorer 1000 v2 519 € https://fr.jackery.com/products/explorer-1000-v2-portable-power-station",
"tip": ""
},
{
"id": "G047",
"category": "Énergie",
"name": "Groupe électrogène inverter",
"model": "Mecafer MF3000i 3000 W (essence)",
"qty": 1,
"weight_g": null,
"price_eur": 399,
"price_status": "relevé",
"url": "https://www.castorama.fr/groupe-electrogene-3000-w-carburant-sp95-et-sp98-autonomie-8-h-l-43-x-l-50-5-x-h-51-5-cm-mecafer-mf3000i/3283494501308_CAFR.prd",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "maison",
"note": "Exclusivement en extérieur (monoxyde de carbone). Entrée : Mercure MC2600 2100 W 299,90 €. Stocker l'essence avec stabilisant, en jerrican homologué.",
"tip": "Exclusivement en extérieur (monoxyde de carbone). Stocker l'essence avec stabilisant, en jerrican homologué."
},
{
"id": "G048",
"category": "Communication",
"name": "Radio d'urgence dynamo/solaire (FM/MW/SW)",
"model": "HanRongDa HRD-908",
"qty": 1,
"weight_g": null,
"price_eur": 49.2,
"price_status": "relevé",
"url": "https://www.passion-radio.fr/radio-durgence/96264-3118.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Page affiche 41,00 € HT ; TTC calculé (TVA 20 %). Entrée : PNI DYN300 FM/AM/SW 34,57 € HT ≈ 41,48 € TTC https://www.passion-radio.fr/radio-durgence/pni-dyn300-3154.html . Radio à piles simple : 16,96 € https://www.lyophilise.fr/15539-radio-urgence-a-piles.html",
"tip": ""
},
{
"id": "G049",
"category": "Communication",
"name": "Récepteur ondes courtes (SSB)",
"model": "Tecsun PL-330",
"qty": 1,
"weight_g": null,
"price_eur": 103.92,
"price_status": "relevé",
"url": "https://www.passion-radio.fr/scanner/PL330-2665.html",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "maison",
"note": "Page affiche 86,60 € HT (statut 'BackOrder') ; TTC calculé.",
"tip": ""
},
{
"id": "G050",
"category": "Communication",
"name": "Talkie-walkie PMR446 (sans licence)",
"model": "Motorola Talkabout T42 (paire)",
"qty": 1,
"weight_g": null,
"price_eur": 34.66,
"price_status": "relevé",
"url": "https://www.passion-radio.fr/sans-licence/t42bluepack-2689.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "les deux",
"note": "Page affiche 28,88 € HT ; TTC calculé. Plus robuste : Midland G7 Pro 63,95 € (en rupture) https://www.onedirect.fr/produits/midland-g7-pro . Un Baofeng UV-5R n'est PAS autorisé en émission sans licence radioamateur ni homologué PMR446.",
"tip": "Un Baofeng UV-5R n'est PAS autorisé en émission sans licence radioamateur ni homologué PMR446."
},
{
"id": "G051",
"category": "Communication",
"name": "Sifflet",
"model": "CAO Outdoor sifflet de secours",
"qty": 1,
"weight_g": 9,
"price_eur": 4.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/8108-sifflet-de-secours-avec-capuchon-cao-outdoor.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "",
"tip": ""
},
{
"id": "G052",
"category": "Communication",
"name": "Miroir de signalisation",
"model": "BCB",
"qty": 1,
"weight_g": 15,
"price_eur": 3.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/12325-miroir-de-signalisation-bcb.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "",
"tip": ""
},
{
"id": "G053",
"category": "Navigation",
"name": "Boussole à plaque",
"model": "Silva Ranger S",
"qty": 1,
"weight_g": 58,
"price_eur": 47.9,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/14204-boussole-silva-ranger-s.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Entrée : Silva Field 27,95 € (en rupture) https://www.lyophilise.fr/15778-boussole-silva-field.html",
"tip": ""
},
{
"id": "G054",
"category": "Navigation",
"name": "Carte IGN TOP 25",
"model": "Carte IGN TOP 25 de votre secteur (ex. 2432ET Massif du Sancy)",
"qty": 2,
"weight_g": null,
"price_eur": 14.3,
"price_status": "relevé",
"url": "https://boutique.ign.fr/cartes/cartes-randonnee-france/top25-seriebleue/top25-seriebleue-france.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Prix uniforme 14,30 € observé sur la liste TOP 25 de la boutique IGN. Choisir domicile + itinéraire d'évacuation.",
"tip": "Choisir la carte du domicile et celles de l'itinéraire d'évacuation."
},
{
"id": "G055",
"category": "Navigation",
"name": "GPS de randonnée",
"model": "Garmin eTrex SE",
"qty": 1,
"weight_g": null,
"price_eur": 149,
"price_status": "estimation",
"url": "https://www.decathlon.fr/search?Ntt=garmin+etrex+se",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "sac",
"note": "Estimation : 149 € (i-run.fr) / 148,90 € (Snowleader) d'après extraits moteur de recherche ; pages en 403, non vérifiées. Fonctionne sur 2 piles AA.",
"tip": "Fonctionne sur 2 piles AA."
},
{
"id": "G056",
"category": "Outils",
"name": "Couteau à lame fixe",
"model": "Morakniv Companion",
"qty": 1,
"weight_g": 120,
"price_eur": 14.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/9317-126-couteau-mora-companion.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Version avec ferro : Companion Spark 36,95 €. Opinel n°7 : 11,50 € (35 g). Port d'arme blanche encadré en France : transporter rangé dans le sac, motif légitime.",
"tip": "Port d'arme blanche encadré en France : transporter rangé dans le sac, avec un motif légitime."
},
{
"id": "G057",
"category": "Outils",
"name": "Couteau suisse",
"model": "Victorinox Huntsman (15 fonctions)",
"qty": 1,
"weight_g": 97,
"price_eur": 38.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/9018-couteau-suisse-victorinox-huntsman-15-outils-rouge.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Entrée : Victorinox Camper 29,95 €.",
"tip": ""
},
{
"id": "G058",
"category": "Outils",
"name": "Pince multifonction",
"model": "Leatherman Wingman",
"qty": 1,
"weight_g": null,
"price_eur": 89,
"price_status": "relevé",
"url": "https://aciertrempe.fr/multifonctions/poche/pince-multifonction-leatherman-wingman/",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "les deux",
"note": "Haut de gamme : Leatherman Signal 159 € (213 g, en rupture) https://www.lyophilise.fr/7238-pince-multifonction-leatherman-signal-19-outils.html",
"tip": ""
},
{
"id": "G059",
"category": "Outils",
"name": "Scie pliante",
"model": "Silky Pocketboy 170-10",
"qty": 1,
"weight_g": 227,
"price_eur": 44.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/11026-scie-pliante-silky-pocketboy-170-10.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "les deux",
"note": "",
"tip": ""
},
{
"id": "G060",
"category": "Outils",
"name": "Paracorde",
"model": "Paracorde réfléchissante SOL",
"qty": 1,
"weight_g": 158,
"price_eur": 14.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/10187-paracorde-reflechissante-sol.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Paracorde 550 avec mousqueton 14,90 € (en rupture).",
"tip": ""
},
{
"id": "G061",
"category": "Outils",
"name": "Duct tape",
"model": "SOL Duct tape (2 mini-rouleaux)",
"qty": 1,
"weight_g": 16,
"price_eur": 7.9,
"price_status": "relevé",
"url": "https://www.rayonrando.com/fr/accessoires-pour-tente/5052-ruban-adhesif-en-toile-duct-tape.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Maison : Scotch Extremium 25 m x 48 mm, 14,50 € https://www.castorama.fr/ruban-adhesif-toile-de-reparation-scotch-extremium-25-x-48-mm-noir/4054596696419_CAFR.prd",
"tip": ""
},
{
"id": "G062",
"category": "Outils",
"name": "Pelle / truelle",
"model": "Sea to Summit mini-pelle (hygiène)",
"qty": 1,
"weight_g": 87,
"price_eur": 9.85,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/16107-mini-pelle-sea-to-summit.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Maison : pelle-pioche pliante Outils Perrin 38,40 € (marketplace) https://www.castorama.fr/departments/outils-perrin-pelle-pioche-pliante-de-camping-pelle-us/3239041551159_CAFR.prd",
"tip": ""
},
{
"id": "G063",
"category": "Outils",
"name": "Hachette",
"model": "Magnusson hachette 600 g manche composite",
"qty": 1,
"weight_g": null,
"price_eur": 16.5,
"price_status": "relevé",
"url": "https://www.castorama.fr/hachette-600g-avec-manche-composite-magnusson/5059340086446_CAFR.prd",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "maison",
"note": "",
"tip": ""
},
{
"id": "G064",
"category": "Santé",
"name": "Trousse de premiers secours",
"model": "Care Plus First Aid Kit Emergency",
"qty": 1,
"weight_g": 470,
"price_eur": 40.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/6731-kit-de-premier-secours-care-plus-emergency.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Entrée : trousse Pharmavoyage Premiers soins 11,95 € (215 g) https://www.lyophilise.fr/8958-trousse-de-secours-pharmavoyage-premiers-soins.html . Ajouter médicaments personnels + copie des ordonnances.",
"tip": "Ajouter médicaments personnels + copie des ordonnances."
},
{
"id": "G065",
"category": "Santé",
"name": "Garrot tourniquet",
"model": "C-A-T Gen 7 (CAT Resources)",
"qty": 1,
"weight_g": null,
"price_eur": 42.99,
"price_status": "relevé",
"url": "https://www.tacmat.fr/produit/garrot-touniquet-cat-gen-7/",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "les deux",
"note": "Aussi 49,99 € chez ylea.eu. Nombreuses contrefaçons : acheter chez un revendeur identifié. Se former (PSC1 / 'Stop the Bleed').",
"tip": "Se former (PSC1 / 'Stop the Bleed')."
},
{
"id": "G066",
"category": "Santé",
"name": "Pansement compressif israélien",
"model": "Pansement israélien (Persys Medical)",
"qty": 2,
"weight_g": null,
"price_eur": 9.99,
"price_status": "relevé",
"url": "https://www.tacmat.fr/produit/pansement-bandage-israelien-persys-medical/",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "les deux",
"note": "Vérifier la taille (4\" / 6\") sur la fiche.",
"tip": "Vérifier la taille (4\" / 6\") sur la fiche."
},
{
"id": "G067",
"category": "Santé",
"name": "Comprimés d'iode",
"model": "Iodure de potassium 65 mg (boîte de 10)",
"qty": 1,
"weight_g": null,
"price_eur": 0,
"price_status": "relevé",
"url": "https://pharmactu.fr/articles/comprimes-iode-pharmacie-distribution-centrales-nucleaires-septembre-2026",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "maison",
"note": "Gratuit, sans ordonnance, en pharmacie pour les résidents/travailleurs à 0-20 km d'une centrale (campagne à partir de sept. 2026, selon pharmactu.fr). À prendre UNIQUEMENT sur ordre du préfet. Hors zone : pas de prix vérifié.",
"tip": "À prendre UNIQUEMENT sur ordre du préfet."
},
{
"id": "G068",
"category": "Santé",
"name": "Masques FFP2",
"model": "Masque FFP2 NR – boîte de 20",
"qty": 1,
"weight_g": null,
"price_eur": 3.89,
"price_status": "relevé",
"url": "https://www.pharma-gdd.com/fr/masque-ffp2-nr-d",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Boîte de 10 : 2,39 €.",
"tip": ""
},
{
"id": "G069",
"category": "Santé",
"name": "Masques FFP3",
"model": "Site FFP3 (10 pièces)",
"qty": 1,
"weight_g": null,
"price_eur": 27.9,
"price_status": "relevé",
"url": "https://www.castorama.fr/masque-anti-poussiere-ffp3-site-10-pieces/5059340013848_CAFR.prd",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "maison",
"note": "Protection poussières/fumées ; ne protège pas des gaz.",
"tip": "Protection poussières/fumées ; ne protège pas des gaz."
},
{
"id": "G070",
"category": "Santé",
"name": "Gants nitrile jetables",
"model": "Site nitrile T9 (x100)",
"qty": 1,
"weight_g": null,
"price_eur": 8.89,
"price_status": "relevé",
"url": "https://www.castorama.fr/gant-jetable-en-nitrile-pour-la-manipulation-generale-site-taille-9-blanc-lot-de-100/5059340642758_CAFR.prd",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Choisir sa taille.",
"tip": "Choisir sa taille."
},
{
"id": "G071",
"category": "Hygiène",
"name": "Savon (sac)",
"model": "Sea to Summit savon en feuilles (corps)",
"qty": 1,
"weight_g": 14,
"price_eur": 4.46,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/9924-savons-en-feuilles-sea-to-summit-corps.html",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "sac",
"note": "Prix barré 4,95 €. Maison : cube de savon de Marseille 500 g, 8,59 € https://www.castorama.fr/cube-de-savon-de-marseille-la-corvette-savonnerie-du-midi-extra-pur-500gr/3182612705027_CAFR.prd",
"tip": ""
},
{
"id": "G072",
"category": "Hygiène",
"name": "Gel hydroalcoolique",
"model": "Wyritol 300 ml flacon pompe",
"qty": 1,
"weight_g": null,
"price_eur": 6.99,
"price_status": "relevé",
"url": "https://www.castorama.fr/gel-hydroalcoolique-flacon-pompe-300ml-wyritol/3661295615019_CAFR.prd",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "",
"tip": ""
},
{
"id": "G073",
"category": "Hygiène",
"name": "Papier toilette",
"model": "Pure Soft 12 rouleaux",
"qty": 2,
"weight_g": null,
"price_eur": 2.58,
"price_status": "relevé",
"url": "https://www.action.com/fr-fr/search/?q=papier%20toilette",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "maison",
"note": "Prix lu sur la page de résultats Action (fiche produit 403). Sac : lingettes compressées Océale dès 3,95 € https://www.lyophilise.fr/9468-175-lingettes-compressees-oceale.html",
"tip": ""
},
{
"id": "G074",
"category": "Hygiène",
"name": "Lingettes humides",
"model": "Teddy Care 60 pièces",
"qty": 2,
"weight_g": null,
"price_eur": 0.99,
"price_status": "relevé",
"url": "https://www.action.com/fr-fr/search/?q=lingettes%20humides%20teddy%20care",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "les deux",
"note": "Prix lu sur la page de résultats Action.",
"tip": ""
},
{
"id": "G075",
"category": "Hygiène",
"name": "Sacs poubelle 100 L",
"model": "10 sacs poubelle transparents 100 L",
"qty": 2,
"weight_g": null,
"price_eur": 4.29,
"price_status": "relevé",
"url": "https://www.castorama.fr/10-sacs-poubelle-transparents-jetables-100l/3570701190074_CAFR.prd",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "les deux",
"note": "Multi-usages : toilettes de fortune, étanchéité, poncho.",
"tip": "Multi-usages : toilettes de fortune, étanchéité, poncho."
},
{
"id": "G076",
"category": "Hygiène",
"name": "Toilettes sèches / portables",
"model": "Thetford Campa Potti Cube",
"qty": 1,
"weight_g": null,
"price_eur": 119.9,
"price_status": "relevé",
"url": "https://www.castorama.fr/toilettes-portables-thetford-campa-potti-cube-capacite-du-reservoir-d-eau-21-litres-l-38-3-x-p-42-7-x-h-41-4-cm/8710315024609_CAFR.prd",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "maison",
"note": "Solution économique : seau 20 L à couvercle + sacs poubelle + sciure/litière. Toilettes sèches à séparateur (fabricant FR, marketplace) dès 336 €.",
"tip": "Solution économique : seau 20 L à couvercle + sacs poubelle + sciure ou litière."
},
{
"id": "G077",
"category": "Documents/argent",
"name": "Pochette étanche documents",
"model": "aLoksak x2 – 33,7 x 26,7 cm",
"qty": 1,
"weight_g": 34.5,
"price_eur": 21.95,
"price_status": "relevé",
"url": "https://www.lyophilise.fr/8005-sachets-etanches-aloksak-x-2-337-x-267-cm.html",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "sac",
"note": "Photocopies pièces d'identité, ordonnances, contrats + argent liquide en petites coupures (repère du guide gouvernemental).",
"tip": "Photocopies pièces d'identité, ordonnances, contrats + argent liquide en petites coupures (repère du guide gouvernemental)."
},
{
"id": "G078",
"category": "Documents/argent",
"name": "Clé USB chiffrée (matérielle)",
"model": "Kingston IronKey Keypad 200 – 32 Go",
"qty": 1,
"weight_g": null,
"price_eur": 184.96,
"price_status": "relevé",
"url": "https://www.ldlc.com/fiche/PB00522245.html",
"source_date": "2026-09-30",
"priority": "optionnel",
"scope": "sac",
"note": "Même prix chez materiel.net. Entrée : Kingston IronKey Vault Privacy 50C 16 Go 99,95 € https://www.ldlc.com/fiche/PB00665145.html . Alternative gratuite : conteneur VeraCrypt sur clé standard.",
"tip": "Alternative gratuite : conteneur VeraCrypt sur clé standard."
},
{
"id": "G079",
"category": "Sécurité",
"name": "Extincteur",
"model": "Kidde 2 kg ABC",
"qty": 1,
"weight_g": null,
"price_eur": 44.9,
"price_status": "relevé",
"url": "https://www.castorama.fr/extincteur-polyvalent-kidde-2-kg-abc/0090008462962_CAFR.prd",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "maison",
"note": "Entrée : Kidde 1 kg ABC 29,90 €. Aérosol eau+mousse Lifebox 750 ml 17,50 €.",
"tip": ""
},
{
"id": "G080",
"category": "Sécurité",
"name": "Détecteur de fumée",
"model": "Kidde 10Y29 (pile 10 ans)",
"qty": 1,
"weight_g": null,
"price_eur": 21.9,
"price_status": "relevé",
"url": "https://www.castorama.fr/detecteur-de-fumee-anti-vandalisme-kidde-10y29/0047871097531_CAFR.prd",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "maison",
"note": "Obligatoire dans tout logement en France. Entrée : Kidde 3Y29 12,90 €.",
"tip": "Obligatoire dans tout logement en France."
},
{
"id": "G081",
"category": "Sécurité",
"name": "Détecteur de monoxyde de carbone",
"model": "Kidde 7CO",
"qty": 1,
"weight_g": null,
"price_eur": 28.9,
"price_status": "relevé",
"url": "https://www.castorama.fr/detecteur-de-monoxyde-de-carbone-kidde-7co/0047871313228_CAFR.prd",
"source_date": "2026-09-30",
"priority": "essentiel",
"scope": "maison",
"note": "Indispensable si réchaud/chauffage d'appoint/groupe électrogène.",
"tip": "Indispensable si réchaud/chauffage d'appoint/groupe électrogène."
},
{
"id": "G082",
"category": "Stockage maison",
"name": "Étagère métal",
"model": "GoodHome Ryle 179 x 90 x 40 cm",
"qty": 1,
"weight_g": null,
"price_eur": 34.9,
"price_status": "relevé",
"url": "https://www.castorama.fr/etagere-de-garage-en-acier-thermo-laque-noir-h-179-x-l-90-x-p-40-cm-goodhome-ryle/5063022514264_CAFR.prd",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "maison",
"note": "Charge lourde : étagère 4 plateaux L.180 cm 79 €.",
"tip": ""
},
{
"id": "G083",
"category": "Stockage maison",
"name": "Malles de rangement 60 L",
"model": "Tontarelli OPP 60 L avec couvercle",
"qty": 3,
"weight_g": null,
"price_eur": 16.9,
"price_status": "relevé",
"url": "https://www.castorama.fr/malle-de-rangement-60-l-noire-avec-couvercle-tontarelli-opp/8009404277201_CAFR.prd",
"source_date": "2026-09-30",
"priority": "recommandé",
"scope": "maison",
"note": "Lot de 3 : 50,70 €. Étiqueter date de péremption, rotation FIFO (premier entré, premier sorti).",
"tip": "Étiqueter la date de péremption, rotation FIFO (premier entré, premier sorti)."
}
];
